#include "cli/cli.h"

#include "egress_schemas.h" /* generated by maelys-cli-embed from cli/schemas/ */

/* Application identity and command catalog. Everything public about the
 * command line (patterns, options, effects, output modes, exit codes) is
 * declared here and served by libmaelys_cli: help, version, describe,
 * completion, parsing, rendering and error envelopes are the framework's. */

static const maelys_cli_option_t config_options[] = {
    {MAELYS_CLI_PATH("config", "FILE",
     "Complete daemon configuration file declaring schema_version = 1."),
     .required = 1},
};

static const maelys_cli_operand_t exec_operands[] = {
    {MAELYS_CLI_OPERAND_KIND("program", "Absolute path of the program to start.",
     MAELYS_CLI_VALUE_ABSOLUTE_PATH)},
    {MAELYS_CLI_OPERAND_REST("argument", "Argument passed to the program, verbatim.")},
};

static const maelys_cli_command_t commands[] = {
    {MAELYS_CLI_READ("config.describe", "config describe",
     "Describe every supported configuration key and constraint.",
     egress_cli_command_config_describe),
     MAELYS_CLI_SCHEMA(egress_config_describe_schema)},
    {MAELYS_CLI_READ("config.validate", "config validate",
     "Validate a complete configuration without opening listeners; exit 2 "
     "reports violations in data.",
     egress_cli_command_config_validate),
     MAELYS_CLI_OPTIONS(config_options),
     MAELYS_CLI_SCHEMA(egress_config_validate_schema)},
    {MAELYS_CLI_PROTOCOL_STREAM("serve", "serve",
     "Start mediation and run until SIGINT or SIGTERM; stdout carries the "
     "lifecycle JSON Lines stream.",
     egress_cli_command_serve, "maelys-egress-lifecycle/1"),
     MAELYS_CLI_OPTIONS(config_options)},
    {MAELYS_CLI_PROTOCOL_STREAM("channel.broker", "channel broker",
     "Serve native channels through a private Unix socket until SIGINT or SIGTERM; "
     "stdout carries the lifecycle JSON Lines stream.",
     egress_cli_command_channel_broker, "maelys-egress-lifecycle/1"),
     MAELYS_CLI_OPTIONS(config_options)},
    {MAELYS_CLI_STREAM("channel.exec", "channel exec",
     "Start one program with a native channel on an inherited descriptor and exit "
     "with its status, 128 + signal if a signal ended it; stdout and stderr are the "
     "program's. Not a sandbox: the program keeps its own network access.",
     egress_cli_command_channel_exec),
     MAELYS_CLI_OPTIONS(config_options),
     MAELYS_CLI_OPERANDS(exec_operands)},
};

int main(int argc, char **argv) {
    maelys_cli_app_t app = {
        .program = "maelys-egress",
        .product = "Maelys Egress",
        .version = maelys_egress_version_string(),
        .summary = "policy-enforced forward proxy for sandboxed workloads",
        .commands = commands,
        .command_count = MAELYS_CLI_COUNT(commands),
        .agent_guidance =
            "'serve' and 'channel broker' reserve stdout for maelys-egress-lifecycle/1 JSON Lines: "
            "wait for event == \"ready\", then keep draining receipts and reload "
            "events until the process exits; 'fatal' or a non-zero exit is a "
            "failure. 'config validate' exits 2 when data.valid is false and "
            "lists the violations in data.diagnostics. 'channel exec' leaves stdout "
            "and stderr to the program it starts and exits with that program's "
            "status: a JSON error envelope on stderr means the program never started, "
            "and only then is exit 1 this command's own.",
    };
    return maelys_cli_main(&app, argc, argv);
}
