#include "cli/cli.h"

#include "egress_schemas.h" /* generated by maelys-cli-embed from cli/schemas/ */

/* Application identity and command catalog. Everything public about the
 * command line (patterns, options, effects, output modes, exit codes) is
 * declared here and served by libmaelys_cli: help, version, describe,
 * parsing, rendering and error envelopes are the framework's. */

static const maelys_cli_option_t config_options[] = {
    {MAELYS_CLI_PATH("config", "FILE",
     "Complete daemon configuration file declaring schema_version = 1."),
     .required = 1},
};

static const maelys_cli_operand_t completion_operands[] = {
    {MAELYS_CLI_OPERAND("SHELL", "Completion dialect: bash, zsh or fish.")},
};

static const maelys_cli_command_t commands[] = {
    {MAELYS_CLI_READ("config.describe", "config describe",
     "Describe every supported configuration key and constraint.",
     egress_cli_command_config_describe),
     MAELYS_CLI_SCHEMA(egress_config_describe_schema)},
    {MAELYS_CLI_READ("config.validate", "config validate",
     "Validate a complete configuration without opening listeners; exit 2 "
     "reports violations in data.",
     egress_cli_command_config_validate),
     MAELYS_CLI_OPTIONS(config_options),
     MAELYS_CLI_SCHEMA(egress_config_validate_schema)},
    {MAELYS_CLI_PROTOCOL_STREAM("serve", "serve",
     "Start mediation and run until SIGINT or SIGTERM; stdout carries the "
     "lifecycle JSON Lines stream.",
     egress_cli_command_serve, "maelys-egress-lifecycle/1"),
     MAELYS_CLI_OPTIONS(config_options)},
    {MAELYS_CLI_READ("completion", "completion",
     "Generate completion code for bash, zsh or fish.",
     egress_cli_command_completion),
     MAELYS_CLI_OPERANDS(completion_operands),
     MAELYS_CLI_SCHEMA(egress_completion_schema)},
};

int main(int argc, char **argv) {
    maelys_cli_app_t app = {
        .program = "maelys-egress",
        .product = "Maelys Egress",
        /* The build macro, not the library string: the release-neutral
         * contract build (make cli-reference, make contract-check) overrides
         * it to 0.0.0 so generated references do not churn per release. */
        .version = MAELYS_EGRESS_BUILD_VERSION,
        .summary = "policy-enforced forward proxy for sandboxed workloads",
        .commands = commands,
        .command_count = MAELYS_CLI_COUNT(commands),
        .agent_guidance =
            "'serve' reserves stdout for maelys-egress-lifecycle/1 JSON Lines: "
            "wait for event == \"ready\", then keep draining receipts and reload "
            "events until the process exits; 'fatal' or a non-zero exit is a "
            "failure. 'config validate' exits 2 when data.valid is false and "
            "lists the violations in data.diagnostics.",
    };
    return maelys_cli_main(&app, argc, argv);
}
