/* Generated by tools/freeze_abi.py from v0.20.0: include/maelys/egress_tls.h.
 * Do not edit. Include after the current headers, once with
 * MAELYS_ABI_FLOOR_PRESENCE defined and once without. While this compiles,
 * every declaration of that revision still holds as it was. One fragment
 * per revision the interface still serves; a break that raises the floor
 * removes the fragments below it, in the same change. */
#include <stddef.h>
#ifdef MAELYS_ABI_FLOOR_PRESENCE
void abi_tls_1_presence(void);
void abi_tls_1_presence(void) {
    (void)sizeof(maelys_egress_tls_provider_t *);
    (void)sizeof(maelys_egress_tls_role_t *);
    (void)sizeof(maelys_egress_tls_step_t *);
    (void)sizeof(maelys_egress_tls_ops_t *);
    (void)maelys_egress_tls_provider_create;
    (void)maelys_egress_tls_provider_name;
    (void)maelys_egress_tls_provider_retain;
    (void)maelys_egress_tls_provider_release;
}
#else

/* include/maelys/egress_tls.h at v0.20.0 */
typedef struct maelys_egress_tls_provider maelys_egress_tls_provider_t;
_Static_assert(MAELYS_EGRESS_TLS_CLIENT == (1) + 0, "MAELYS_EGRESS_TLS_CLIENT moved since v0.20.0");
_Static_assert(MAELYS_EGRESS_TLS_SERVER == (2) + 0, "MAELYS_EGRESS_TLS_SERVER moved since v0.20.0");
_Static_assert(MAELYS_EGRESS_TLS_COMPLETE == (0) + 0, "MAELYS_EGRESS_TLS_COMPLETE moved since v0.20.0");
_Static_assert(MAELYS_EGRESS_TLS_WANT_READ == (0) + 1, "MAELYS_EGRESS_TLS_WANT_READ moved since v0.20.0");
_Static_assert(MAELYS_EGRESS_TLS_WANT_WRITE == (0) + 2, "MAELYS_EGRESS_TLS_WANT_WRITE moved since v0.20.0");
_Static_assert(MAELYS_EGRESS_TLS_CLOSED == (0) + 3, "MAELYS_EGRESS_TLS_CLOSED moved since v0.20.0");
_Static_assert(MAELYS_EGRESS_TLS_FAILED == (0) + 4, "MAELYS_EGRESS_TLS_FAILED moved since v0.20.0");
typedef struct abi_tls_1_maelys_egress_tls_ops {
    unsigned int abi_version;
    const char *name;
    maelys_egress_result_t (*session_create)( void *context, maelys_egress_tls_role_t role, int fd, const char *server_name, void **out_session, char **out_error);
    maelys_egress_tls_step_t (*handshake)(void *context, void *session);
    maelys_egress_tls_step_t (*read)( void *context, void *session, void *buffer, size_t capacity, size_t *out_read);
    maelys_egress_tls_step_t (*write)( void *context, void *session, const void *buffer, size_t length, size_t *out_written);
    maelys_egress_tls_step_t (*shutdown)(void *context, void *session);
    const char *(*last_error)(void *context, const void *session);
    void (*session_release)(void *context, void *session);
} abi_tls_1_maelys_egress_tls_ops_t;
_Static_assert(sizeof(maelys_egress_tls_ops_t) == sizeof(abi_tls_1_maelys_egress_tls_ops_t), "maelys_egress_tls_ops_t changed size since v0.20.0");
_Static_assert(offsetof(maelys_egress_tls_ops_t, abi_version) == offsetof(abi_tls_1_maelys_egress_tls_ops_t, abi_version), "maelys_egress_tls_ops_t.abi_version moved since v0.20.0");
_Static_assert(offsetof(maelys_egress_tls_ops_t, name) == offsetof(abi_tls_1_maelys_egress_tls_ops_t, name), "maelys_egress_tls_ops_t.name moved since v0.20.0");
_Static_assert(offsetof(maelys_egress_tls_ops_t, session_create) == offsetof(abi_tls_1_maelys_egress_tls_ops_t, session_create), "maelys_egress_tls_ops_t.session_create moved since v0.20.0");
_Static_assert(offsetof(maelys_egress_tls_ops_t, handshake) == offsetof(abi_tls_1_maelys_egress_tls_ops_t, handshake), "maelys_egress_tls_ops_t.handshake moved since v0.20.0");
_Static_assert(offsetof(maelys_egress_tls_ops_t, read) == offsetof(abi_tls_1_maelys_egress_tls_ops_t, read), "maelys_egress_tls_ops_t.read moved since v0.20.0");
_Static_assert(offsetof(maelys_egress_tls_ops_t, write) == offsetof(abi_tls_1_maelys_egress_tls_ops_t, write), "maelys_egress_tls_ops_t.write moved since v0.20.0");
_Static_assert(offsetof(maelys_egress_tls_ops_t, shutdown) == offsetof(abi_tls_1_maelys_egress_tls_ops_t, shutdown), "maelys_egress_tls_ops_t.shutdown moved since v0.20.0");
_Static_assert(offsetof(maelys_egress_tls_ops_t, last_error) == offsetof(abi_tls_1_maelys_egress_tls_ops_t, last_error), "maelys_egress_tls_ops_t.last_error moved since v0.20.0");
_Static_assert(offsetof(maelys_egress_tls_ops_t, session_release) == offsetof(abi_tls_1_maelys_egress_tls_ops_t, session_release), "maelys_egress_tls_ops_t.session_release moved since v0.20.0");
maelys_egress_result_t maelys_egress_tls_provider_create( const maelys_egress_tls_ops_t *ops, void *context, void (*release_context)(void *context), maelys_egress_tls_provider_t **out_provider, char **out_error);
const char *maelys_egress_tls_provider_name( const maelys_egress_tls_provider_t *provider);
void maelys_egress_tls_provider_retain(maelys_egress_tls_provider_t *provider);
void maelys_egress_tls_provider_release(maelys_egress_tls_provider_t *provider);

#endif
