/* Generated by tools/freeze_abi.py from v0.22.0: include/maelys/egress_channel.h include/maelys/egress_client.h.
 * Do not edit. Include after the current headers, once with
 * MAELYS_ABI_FLOOR_PRESENCE defined and once without. While this compiles,
 * every declaration of that revision still holds as it was: it is the
 * floor the ABI_COMPATIBLE_SINCE macro names. Regenerate only when a
 * break raises that floor, in the same change that raises the macro. */
#include <stddef.h>
#ifdef MAELYS_ABI_FLOOR_PRESENCE
void abi_client_1_presence(void);
void abi_client_1_presence(void) {
    (void)sizeof(maelys_egress_channel_status_t *);
    (void)sizeof(maelys_egress_channel_request_t *);
    (void)sizeof(maelys_egress_channel_response_t *);
    (void)sizeof(maelys_egress_client_result_t *);
    (void)maelys_egress_channel_encode_request;
    (void)maelys_egress_channel_decode_request;
    (void)maelys_egress_channel_encode_response;
    (void)maelys_egress_channel_decode_response;
    (void)maelys_egress_channel_status_string;
    (void)maelys_egress_client_connect;
    (void)maelys_egress_client_result_string;
    (void)maelys_egress_client_error_free;
    (void)maelys_egress_client_abi_version;
}
#else

/* include/maelys/egress_channel.h at v0.22.0 */
_Static_assert((MAELYS_EGRESS_CHANNEL_PROTOCOL_VERSION) == (1u), "MAELYS_EGRESS_CHANNEL_PROTOCOL_VERSION changed since v0.22.0");
_Static_assert((MAELYS_EGRESS_CHANNEL_REQUEST_MAGIC) == (UINT32_C(0x4d454351)), "MAELYS_EGRESS_CHANNEL_REQUEST_MAGIC changed since v0.22.0");
_Static_assert((MAELYS_EGRESS_CHANNEL_RESPONSE_MAGIC) == (UINT32_C(0x4d454350)), "MAELYS_EGRESS_CHANNEL_RESPONSE_MAGIC changed since v0.22.0");
_Static_assert((MAELYS_EGRESS_CHANNEL_PROTOCOL_TCP) == (1u), "MAELYS_EGRESS_CHANNEL_PROTOCOL_TCP changed since v0.22.0");
_Static_assert((MAELYS_EGRESS_CHANNEL_MAX_HOST) == (253u), "MAELYS_EGRESS_CHANNEL_MAX_HOST changed since v0.22.0");
_Static_assert((MAELYS_EGRESS_CHANNEL_REQUEST_HEADER_SIZE) == (10u), "MAELYS_EGRESS_CHANNEL_REQUEST_HEADER_SIZE changed since v0.22.0");
_Static_assert((MAELYS_EGRESS_CHANNEL_REQUEST_MAX_SIZE) == ((MAELYS_EGRESS_CHANNEL_REQUEST_HEADER_SIZE + MAELYS_EGRESS_CHANNEL_MAX_HOST)), "MAELYS_EGRESS_CHANNEL_REQUEST_MAX_SIZE changed since v0.22.0");
_Static_assert((MAELYS_EGRESS_CHANNEL_RESPONSE_SIZE) == (8u), "MAELYS_EGRESS_CHANNEL_RESPONSE_SIZE changed since v0.22.0");
_Static_assert(MAELYS_EGRESS_CHANNEL_OK == (0) + 0, "MAELYS_EGRESS_CHANNEL_OK moved since v0.22.0");
_Static_assert(MAELYS_EGRESS_CHANNEL_DENIED == (1) + 0, "MAELYS_EGRESS_CHANNEL_DENIED moved since v0.22.0");
_Static_assert(MAELYS_EGRESS_CHANNEL_TIMEOUT == (2) + 0, "MAELYS_EGRESS_CHANNEL_TIMEOUT moved since v0.22.0");
_Static_assert(MAELYS_EGRESS_CHANNEL_CANCELLED == (3) + 0, "MAELYS_EGRESS_CHANNEL_CANCELLED moved since v0.22.0");
_Static_assert(MAELYS_EGRESS_CHANNEL_MALFORMED == (4) + 0, "MAELYS_EGRESS_CHANNEL_MALFORMED moved since v0.22.0");
_Static_assert(MAELYS_EGRESS_CHANNEL_UNSUPPORTED == (5) + 0, "MAELYS_EGRESS_CHANNEL_UNSUPPORTED moved since v0.22.0");
_Static_assert(MAELYS_EGRESS_CHANNEL_RESOURCE == (6) + 0, "MAELYS_EGRESS_CHANNEL_RESOURCE moved since v0.22.0");
_Static_assert(MAELYS_EGRESS_CHANNEL_INTERNAL == (7) + 0, "MAELYS_EGRESS_CHANNEL_INTERNAL moved since v0.22.0");
typedef struct frozen_maelys_egress_channel_request {
    uint8_t version;
    uint8_t protocol;
    uint16_t port;
    uint16_t host_length;
    char host[MAELYS_EGRESS_CHANNEL_MAX_HOST + 1u];
} frozen_maelys_egress_channel_request_t;
_Static_assert(sizeof(maelys_egress_channel_request_t) == sizeof(frozen_maelys_egress_channel_request_t), "maelys_egress_channel_request_t changed size since v0.22.0");
_Static_assert(offsetof(maelys_egress_channel_request_t, version) == offsetof(frozen_maelys_egress_channel_request_t, version), "maelys_egress_channel_request_t.version moved since v0.22.0");
_Static_assert(offsetof(maelys_egress_channel_request_t, protocol) == offsetof(frozen_maelys_egress_channel_request_t, protocol), "maelys_egress_channel_request_t.protocol moved since v0.22.0");
_Static_assert(offsetof(maelys_egress_channel_request_t, port) == offsetof(frozen_maelys_egress_channel_request_t, port), "maelys_egress_channel_request_t.port moved since v0.22.0");
_Static_assert(offsetof(maelys_egress_channel_request_t, host_length) == offsetof(frozen_maelys_egress_channel_request_t, host_length), "maelys_egress_channel_request_t.host_length moved since v0.22.0");
_Static_assert(offsetof(maelys_egress_channel_request_t, host) == offsetof(frozen_maelys_egress_channel_request_t, host), "maelys_egress_channel_request_t.host moved since v0.22.0");
typedef struct frozen_maelys_egress_channel_response {
    uint8_t version;
    uint8_t status;
    uint16_t reserved;
} frozen_maelys_egress_channel_response_t;
_Static_assert(sizeof(maelys_egress_channel_response_t) == sizeof(frozen_maelys_egress_channel_response_t), "maelys_egress_channel_response_t changed size since v0.22.0");
_Static_assert(offsetof(maelys_egress_channel_response_t, version) == offsetof(frozen_maelys_egress_channel_response_t, version), "maelys_egress_channel_response_t.version moved since v0.22.0");
_Static_assert(offsetof(maelys_egress_channel_response_t, status) == offsetof(frozen_maelys_egress_channel_response_t, status), "maelys_egress_channel_response_t.status moved since v0.22.0");
_Static_assert(offsetof(maelys_egress_channel_response_t, reserved) == offsetof(frozen_maelys_egress_channel_response_t, reserved), "maelys_egress_channel_response_t.reserved moved since v0.22.0");
size_t maelys_egress_channel_encode_request( const char *host, uint16_t port, unsigned char *out, size_t capacity);
maelys_egress_channel_status_t maelys_egress_channel_decode_request( const unsigned char *bytes, size_t length, maelys_egress_channel_request_t *out, const char **out_reason);
size_t maelys_egress_channel_encode_response( maelys_egress_channel_status_t status, unsigned char *out, size_t capacity);
int maelys_egress_channel_decode_response( const unsigned char *bytes, size_t length, maelys_egress_channel_response_t *out, const char **out_reason);
const char *maelys_egress_channel_status_string( maelys_egress_channel_status_t status);

/* include/maelys/egress_client.h at v0.22.0 */
_Static_assert(MAELYS_EGRESS_CLIENT_OK == (0) + 0, "MAELYS_EGRESS_CLIENT_OK moved since v0.22.0");
_Static_assert(MAELYS_EGRESS_CLIENT_ERR_ARGUMENT == (0) + 1, "MAELYS_EGRESS_CLIENT_ERR_ARGUMENT moved since v0.22.0");
_Static_assert(MAELYS_EGRESS_CLIENT_ERR_IO == (0) + 2, "MAELYS_EGRESS_CLIENT_ERR_IO moved since v0.22.0");
_Static_assert(MAELYS_EGRESS_CLIENT_ERR_UNANSWERED == (0) + 3, "MAELYS_EGRESS_CLIENT_ERR_UNANSWERED moved since v0.22.0");
_Static_assert(MAELYS_EGRESS_CLIENT_ERR_PROTOCOL == (0) + 4, "MAELYS_EGRESS_CLIENT_ERR_PROTOCOL moved since v0.22.0");
_Static_assert(MAELYS_EGRESS_CLIENT_ERR_DENIED == (0) + 5, "MAELYS_EGRESS_CLIENT_ERR_DENIED moved since v0.22.0");
_Static_assert(MAELYS_EGRESS_CLIENT_ERR_TIMEOUT == (0) + 6, "MAELYS_EGRESS_CLIENT_ERR_TIMEOUT moved since v0.22.0");
_Static_assert(MAELYS_EGRESS_CLIENT_ERR_CANCELLED == (0) + 7, "MAELYS_EGRESS_CLIENT_ERR_CANCELLED moved since v0.22.0");
_Static_assert(MAELYS_EGRESS_CLIENT_ERR_UNSUPPORTED == (0) + 8, "MAELYS_EGRESS_CLIENT_ERR_UNSUPPORTED moved since v0.22.0");
_Static_assert(MAELYS_EGRESS_CLIENT_ERR_RESOURCE == (0) + 9, "MAELYS_EGRESS_CLIENT_ERR_RESOURCE moved since v0.22.0");
_Static_assert(MAELYS_EGRESS_CLIENT_ERR_INTERNAL == (0) + 10, "MAELYS_EGRESS_CLIENT_ERR_INTERNAL moved since v0.22.0");
maelys_egress_client_result_t maelys_egress_client_connect( int channel_fd, const char *host, uint16_t port, uint64_t read_timeout_ms, int *out_stream_fd, char **out_error);
const char *maelys_egress_client_result_string(maelys_egress_client_result_t result);
void maelys_egress_client_error_free(char *error);
unsigned int maelys_egress_client_abi_version(void);

#endif
