/* Generated by tools/freeze_abi.py from v0.20.0: include/maelys/egress_tls_modules.h.
 * Do not edit. Include after the current headers, once with
 * MAELYS_ABI_FLOOR_PRESENCE defined and once without. While this compiles,
 * every declaration of that revision still holds as it was: it is the
 * floor the ABI_COMPATIBLE_SINCE macro names. Regenerate only when a
 * break raises that floor, in the same change that raises the macro. */
#include <stddef.h>
#ifdef MAELYS_ABI_FLOOR_PRESENCE
void abi_tls_files_1_presence(void);
void abi_tls_files_1_presence(void) {
    (void)sizeof(maelys_egress_tls_files_t *);
    (void)maelys_egress_tls_mbedtls_create;
    (void)maelys_egress_tls_wolfssl_create;
}
#else

/* include/maelys/egress_tls_modules.h at v0.20.0 */
typedef struct frozen_maelys_egress_tls_files {
    unsigned int abi_version;
    const char *certificate_file;
    const char *private_key_file;
    const char *ca_file;
    int require_client_certificate;
} frozen_maelys_egress_tls_files_t;
_Static_assert(sizeof(maelys_egress_tls_files_t) == sizeof(frozen_maelys_egress_tls_files_t), "maelys_egress_tls_files_t changed size since v0.20.0");
_Static_assert(offsetof(maelys_egress_tls_files_t, abi_version) == offsetof(frozen_maelys_egress_tls_files_t, abi_version), "maelys_egress_tls_files_t.abi_version moved since v0.20.0");
_Static_assert(offsetof(maelys_egress_tls_files_t, certificate_file) == offsetof(frozen_maelys_egress_tls_files_t, certificate_file), "maelys_egress_tls_files_t.certificate_file moved since v0.20.0");
_Static_assert(offsetof(maelys_egress_tls_files_t, private_key_file) == offsetof(frozen_maelys_egress_tls_files_t, private_key_file), "maelys_egress_tls_files_t.private_key_file moved since v0.20.0");
_Static_assert(offsetof(maelys_egress_tls_files_t, ca_file) == offsetof(frozen_maelys_egress_tls_files_t, ca_file), "maelys_egress_tls_files_t.ca_file moved since v0.20.0");
_Static_assert(offsetof(maelys_egress_tls_files_t, require_client_certificate) == offsetof(frozen_maelys_egress_tls_files_t, require_client_certificate), "maelys_egress_tls_files_t.require_client_certificate moved since v0.20.0");
maelys_egress_result_t maelys_egress_tls_mbedtls_create( const maelys_egress_tls_files_t *files, maelys_egress_tls_provider_t **out_provider, char **out_error);
maelys_egress_result_t maelys_egress_tls_wolfssl_create( const maelys_egress_tls_files_t *files, maelys_egress_tls_provider_t **out_provider, char **out_error);

#endif
