#!/usr/bin/env python3
# SPDX-License-Identifier: MPL-2.0
"""Hold the set of frozen ABI fragments against the two numbers of each interface.

An interface that declares MAELYS_*_ABI_COMPATIBLE_SINCE = S and
MAELYS_*_ABI_VERSION = V serves the revisions S to V. Each of them below V
needs its fragment under tests/public, generated by tools/freeze_abi.py: the
fragment of S alone would not see the removal of a function that a revision
between S and V added. A fragment of V itself is allowed, never required. A
fragment below S or above V names a revision the interface does not serve
and is refused, and tests/public/abi_floor.c must include every fragment
twice, or the compiler never reads it.

    python3 tools/check_abi_fragments.py [ROOT]
"""
import pathlib
import re
import sys

# macro prefix, header that defines the two numbers, fragment name prefix
INTERFACES = (
    ("MAELYS_EGRESS", "include/maelys/egress.h", "abi-"),
    ("MAELYS_EGRESS_CLIENT", "include/maelys/egress_client.h", "abi-client-"),
    ("MAELYS_EGRESS_TLS", "include/maelys/egress_tls.h", "abi-tls-"),
    ("MAELYS_EGRESS_TLS_FILES", "include/maelys/egress_tls_modules.h", "abi-tls-files-"),
)
FRAGMENTS = "tests/public"
FLOOR_SOURCE = "tests/public/abi_floor.c"


def number(text: str, macro: str, header: str) -> int:
    match = re.search(rf"^#define[ \t]+{macro}[ \t]+(\d+)u?[ \t]*$", text, re.M)
    if not match:
        raise SystemExit(f"check_abi_fragments: {header} does not define {macro}")
    return int(match.group(1))


def main() -> int:
    root = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else ".")
    floor_source = (root / FLOOR_SOURCE).read_text(encoding="utf-8")
    errors, claimed, summary = [], set(), []
    for prefix, header, stem in INTERFACES:
        text = (root / header).read_text(encoding="utf-8")
        since = number(text, f"{prefix}_ABI_COMPATIBLE_SINCE", header)
        version = number(text, f"{prefix}_ABI_VERSION", header)
        if since > version:
            errors.append(f"{header}: {prefix}_ABI_COMPATIBLE_SINCE ({since}) is above "
                          f"{prefix}_ABI_VERSION ({version})")
            continue
        present = {}
        for path in (root / FRAGMENTS).glob(f"{stem}*.h"):
            match = re.fullmatch(rf"{re.escape(stem)}(\d+)\.h", path.name)
            if match:
                present[int(match.group(1))] = path.name
        claimed.update(present.values())
        for revision in range(since, version):
            if revision not in present:
                errors.append(
                    f"{FRAGMENTS}/{stem}{revision}.h is missing: {prefix} serves revisions "
                    f"{since} to {version}. Generate it with tools/freeze_abi.py from the "
                    f"last tag whose {header} carries revision {revision}")
        for revision, name in sorted(present.items()):
            if revision < since:
                errors.append(f"{FRAGMENTS}/{name} is below the floor {since} of {prefix}: "
                              "remove it in the change that raised the floor")
            elif revision > version:
                errors.append(f"{FRAGMENTS}/{name} is above revision {version} of {prefix}")
            includes = len(re.findall(rf'^#include "{re.escape(name)}"$', floor_source, re.M))
            if includes != 2:
                errors.append(f"{FLOOR_SOURCE} includes {name} {includes} time(s), not twice "
                              "(once under MAELYS_ABI_FLOOR_PRESENCE, once without)")
        summary.append(f"{stem.rstrip('-')} {since}..{version}")
    for path in sorted((root / FRAGMENTS).glob("abi-*.h")):
        if path.name not in claimed:
            errors.append(f"{FRAGMENTS}/{path.name} belongs to no declared interface")
    if errors:
        for error in errors:
            print(f"check_abi_fragments: {error}", file=sys.stderr)
        return 1
    print("abi-floor-check: one fragment per served revision (" + ", ".join(summary) + ")")
    return 0


if __name__ == "__main__":
    sys.exit(main())
