#!/usr/bin/env python3
"""Generate the configuration-key reference from `config describe`.

The command reference and the agent-cli/v2 contract are produced by the
maelys-cli generator; only the Egress configuration grammar lives here.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess


def describe(binary: Path) -> dict:
    completed = subprocess.run(
        [str(binary), "config", "describe", "--format", "json", "--compact",
         "--non-interactive"],
        check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
    )
    if completed.stderr:
        raise RuntimeError(f"config describe polluted stderr: {completed.stderr}")
    envelope = json.loads(completed.stdout)
    if envelope.get("contract") != "agent-cli/v2" or envelope.get("ok") is not True:
        raise RuntimeError("config describe returned an incompatible envelope")
    return envelope["data"]


def markdown(data: dict) -> str:
    lines = [
        "# Configuration key reference",
        "",
        "<!-- Generated by tools/generate_config_reference.py; do not edit. -->",
        "",
        f"Configuration schema version {data['configurationSchemaVersion']}, "
        f"grammar `{data['grammar']}`. TLS listener keys are listed only when the "
        "binary that generated this reference links a TLS module.",
        "",
        "| Key | Type | Required | Repeatable | Secret | Default | Constraint | Meaning |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for key in data["keys"]:
        constraint = key.get("range") or key.get("allowedValues") or ""
        meaning = key["description"]
        if key.get("requires"):
            meaning += f" Requires: `{key['requires']}`."
        if key.get("conflicts"):
            meaning += f" Conflicts: `{key['conflicts']}`."
        default = f"`{key['default']}`" if key.get("default") else ""
        lines.append(
            f"| `{key['name']}` | `{key['type']}` | "
            f"{'yes' if key['required'] else 'no'} | "
            f"{'yes' if key['repeatable'] else 'no'} | "
            f"{'yes' if key['secret'] else 'no'} | {default} | {constraint} | {meaning} |"
        )
    lines.extend(["", "## Cross-key constraints", ""])
    lines.extend(f"- {constraint}" for constraint in data["constraints"])
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--binary", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    arguments = parser.parse_args()
    arguments.output.write_text(markdown(describe(arguments.binary)), encoding="utf-8")
    print(f"generated {arguments.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
